version: '3.8'

services:
  software_phoenix_backend:
    build: .
    container_name: software_phoenix_container
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    depends_on:
      - postgres_db
    restart: always

  postgres_db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - /Users/khgamri/Documents/postgres_data:/var/lib/postgresql/data
    restart: always
